name: belich-legos-r2
channels:
  - conda-forge
  - defaults
dependencies:
  - mpich           # MPI library (you may replace with Intel MPI for better compatibility)
  - hdf5            # HDF5 support (required for NetCDF-4)
  - netcdf-fortran  # Fortran bindings for NetCDF
  - cmake           # CMake for building projects
  - libtool         # For building libraries like Parallel NetCDF
  - autoconf        # For configuring build environments
  - automake        # Automake for build scripts
  - m4              # Required by autoconf
  - make            # Make utility for building
  - hdf5=*=mpi_mpich* # HDF5 with MPI Support
  - mpi4py          # for NetCDF with parallel I/O support
  
# Optional Python bindings for NetCDF
#  - python=3.7.*
#  - netcdf4  # Python interface for NetCDF
  - R=4.1
  - r-base
  - r-essentials

# Install PnetCDF within the environment
# (see instructions)