import copernicusmarine

## MEDSEA_MULTIYEAR_BGC_006_008
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2011.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2012.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2013.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2014.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2015.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2016.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2017.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2018.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2019.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2020.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2021.json")
#copernicusmarine.subset(request_file="reanalysis/request_car_ra_2022.json")

#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2011.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2012.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2013.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2014.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2015.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2016.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2017.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2018.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2019.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2020.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2021.json")
#copernicusmarine.subset(request_file="reanalysis/request_co2_ra_2022.json")

#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2011.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2012.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2013.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2014.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2015.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2016.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2017.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2018.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2019.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2020.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2021.json")
#copernicusmarine.subset(request_file="reanalysis/request_nut_ra_2022.json")

#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2011.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2012.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2013.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2014.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2015.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2016.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2017.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2018.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2019.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2020.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2021.json")
#copernicusmarine.subset(request_file="reanalysis/request_pft_ra_2022.json")

#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2011.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2012.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2013.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2014.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2015.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2016.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2017.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2018.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2019.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2020.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2021.json")
#copernicusmarine.subset(request_file="reanalysis/request_bio_ra_2022.json")

##copernicusmarine.subset(request_file="request_bathy_ra.json")
##copernicusmarine.subset(request_file="request_coord_ra.json")


## MEDSEA_ANALYSISFORECAST_BGC_006_014
#copernicusmarine.subset(request_file="analysis_forecast/request_car_af_2023.json")
#copernicusmarine.subset(request_file="analysis_forecast/request_car_af_2024.json")
copernicusmarine.subset(request_file="analysis_forecast/request_car_af_2025.json")

#copernicusmarine.subset(request_file="analysis_forecast/request_co2_af_2023.json")
#copernicusmarine.subset(request_file="analysis_forecast/request_co2_af_2024.json")
copernicusmarine.subset(request_file="analysis_forecast/request_co2_af_2025.json")

#copernicusmarine.subset(request_file="analysis_forecast/request_nut_af_2023.json")
#copernicusmarine.subset(request_file="analysis_forecast/request_nut_af_2024.json")
copernicusmarine.subset(request_file="analysis_forecast/request_nut_af_2025.json")

#copernicusmarine.subset(request_file="analysis_forecast/request_pft_af_2023.json")
#copernicusmarine.subset(request_file="analysis_forecast/request_pft_af_2024.json")
copernicusmarine.subset(request_file="analysis_forecast/request_pft_af_2025.json")

#copernicusmarine.subset(request_file="analysis_forecast/request_bio_af_2023.json")
#copernicusmarine.subset(request_file="analysis_forecast/request_bio_af_2024.json")
copernicusmarine.subset(request_file="analysis_forecast/request_bio_af_2025.json")

##copernicusmarine.subset(request_file="request_bathy_af.json")
##copernicusmarine.subset(request_file="request_coord_af.json")
##copernicusmarine.subset(request_file="request_opt_af.json")
