      subroutine hot_restart(ichoix)
!______________________________________________________________________
!
! Generalized Arbitrary Lagrangian Eulerian coordinate ocean model
! release 2010.10  - last update: 11-06-10
! Contact: sirocco@aero.obs-mip.fr
! Laboratoire d'Aerologie, 14 Avenue Edouard Belin, F-31400 Toulouse
! http://sirocco.omp.obs-mip.fr/outils/modele/Accueil/modeleAccueil.htm
!
!______________________________________________________________________
      use module_principal
      use module_parallele !#MPI
      implicit none
#ifdef synopsis
       subroutinetitle='hot_restart'
       subroutinedescription=' '
       call main_synopsis(subroutinetitle,subroutinedescription)
#endif

      integer ichoix

!...............................................................................
! modifs: 24/12/02: derniere mise à jour
!                   + bienvenue à restart de la biologie: ichoix=11 & ichoix=22
!         25/12/02: include fichier common bio
!         25/01/03: bienvenue à  à DFVOFL_Z
!         19/03/03: suppression EVA_Z
!         21/08/03: suppression TIDESTEP1
!         11/06/04: changement de noms: chanel9_in  -> chanel9_input
!                                       chanel9_out -> chanel9_output
!                   afin d'éviter les accidents malheureux (rm *out)
!         25/04/05: attribuer un nom "daté" au fichier restart
!         26/04/05: suite du point precedent
!         02/07/06: schema tke forward permet d'eliminer le tableau TKENHZ_Z
!         04/07/06: eliminination serie tableaux ADHY
!         17/01/08: IWAVE renommé IWVE
!         01-06-09: Parallelisation
!         14-06-09: Pas d'ecriture si la sequence de l'iteration en cours
!                   n'est pas achevee
!...............................................................................
      if (ichoix.eq.2.or.ichoix.eq.22) then                             !14-06-0
      if(restart_file_y_or_n==0)then
       write(*,*)
       write(*,*)'erreur dans hot_restart.f: la routine est appellee'
       write(*,*)'alors que la sequence de calcul pour l''iteration'
       write(*,*)'en cours n''est pas terminee.'
       write(*,*)'remplacez votre appel par procedure similaire à'
       write(*,*)'celle utilisee dans date_output.f.'
       stop ' stop dans hot_restart.f'
      endif
      endif

!************************************************************
! Lecture d'un fichier chanel9
!************************************************************
      if (ichoix.eq.11) then !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%>   !24/12/02

      open(unit=9,file='restart_input/chanelbio_'//dom_c,               & !01-06-0
       access='sequential',form='unformatted')

       write(6,*)'lecture chanelbio_input'                             !11/06/04

       read(9)bio_t
       read(9)biosum_t
       read(9)tendancebio_t
       read(9)fluxbio_w
       read(9)wsed
       read(9)river_bio
       read(9)socard
       read(9)kb
       read(9)kbmax
       read(9)kso
       read(9)ksomax

      close(9)

      endif                  !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%>   !24/12/02

      if (ichoix.eq.1) then

      open(unit=9,file='restart_input/chanel9_'//dom_c,                 & !01-06-0
       access='sequential',form='unformatted')

      write(6,*)'lecture chanel9 debut:'

! insere partie_lit_1 debut: SURTOUT NE PAS EFFACER CETTE LIGNE
      read(9)analysetide_u
      read(9)analysetide_v
      read(9)analysetide_w
      read(9)tidepotential_w
      read(9)sshtotide_w
      read(9)sshtidecos_w
      read(9)sshtidesin_w
      read(9)veltidecos_u
      read(9)veltidesin_u
      read(9)veltidecos_v
      read(9)veltidesin_v
      read(9)potidecos_w
      read(9)potidesin_w
      read(9)passetide
      read(9)z1meatide
      read(9)z2meatide
      read(9)frqtide
      read(9)v0tide
      read(9)equitide
      read(9)ftide
      read(9)utide
      read(9)sshmeatide
      read(9)ti0tide
      read(9)tideana_spinup
      read(9)tideana_delta
      read(9)sshtide_cum
      read(9)nutide
      read(9)ktide
      read(9)tideforces
      read(9)tideana_yesno
      read(9)tideana_modulo
      read(9)dz_u
      read(9)dz_v
      read(9)dz_t
      read(9)stokesvortex_u
      read(9)stokesvortex_v
      read(9)depth_t
      read(9)sigma_w
      read(9)dsig_t
      read(9)depth_u
      read(9)depth_v
      read(9)depth_w
      read(9)tridia_out
      read(9)kz_w
      read(9)presgrad_u
      read(9)presgrad_v
      read(9)rhp_t
      read(9)tkll_w
      read(9)tkle_w
      read(9)tken_w
      read(9)mask_t
      read(9)mask_f
      read(9)mask_u
      read(9)mask_v
      read(9)ksl_t
      read(9)vel_u
      read(9)vel_v
      read(9)omega_w
      read(9)veldydz_u
      read(9)veldxdz_v
      read(9)tridia_in
      read(9)tem_t
      read(9)sal_t
      read(9)anyv3d
      read(9)vmi_u
      read(9)vmi_v
      read(9)velobchf_u
      read(9)velobchf_v
      read(9)ssh_obc_hf_w
      read(9)anyvarlr
      read(9)tobc_t
      read(9)sobc_t
      read(9)velobc_u
      read(9)velobc_v
      read(9)dfvofl_w
      read(9)lon_t
      read(9)lat_t
      read(9)lon_u
      read(9)lat_u
      read(9)lon_v
      read(9)lat_v
      read(9)lon_f
      read(9)lat_f
      read(9)fric_u
      read(9)fric_v
      read(9)fric_t
      read(9)velbot3d2d_u
      read(9)velbot3d2d_v
      read(9)cdb_t
      read(9)xflux_t
      read(9)xflux_f
      read(9)yflux_t
      read(9)yflux_f
      read(9)h_w
      read(9)h_u
      read(9)h_v
      read(9)h_f
      read(9)coriolis_t
      read(9)pres3d2d_u
      read(9)pres3d2d_v
      read(9)adve3d2d_u
      read(9)adve3d2d_v
      read(9)dif3d2d_u
      read(9)dif3d2d_v
      read(9)stokesvortex3d2d_u
      read(9)stokesvortex3d2d_v
      read(9)wstress_w
      read(9)z0_w
      read(9)dx_u
      read(9)dx_v
      read(9)dx_t
      read(9)dx_f
      read(9)dy_u
      read(9)dy_v
      read(9)dy_t
      read(9)dy_f
      read(9)dxdy_u
      read(9)dxdy_v
      read(9)dxdy_t
      read(9)albedo_w
      read(9)gridrotcos_t
      read(9)gridrotsin_t
      read(9)sshstokes_w
      read(9)velbar_u
      read(9)velbar_v
      read(9)ssh_ext_w
      read(9)ssh_int_u
      read(9)ssh_int_v
      read(9)ssh_int_w
      read(9)streamf_f
      read(9)hz_u
      read(9)hzdy_u
      read(9)hz_v
      read(9)hzdx_v
      read(9)hz_w
      read(9)vsumsave_u
      read(9)vsumsave_v
      read(9)ssr_w
      read(9)snsf_w
      read(9)precipi_w
      read(9)hssh_w
      read(9)sponge_t
      read(9)zeroleveldepth_u
      read(9)zeroleveldepth_v
      read(9)heatrelax_w
      read(9)velstokes_u
      read(9)velstokes_v
      read(9)t_wave_t
      read(9)hs_wave_t
      read(9)kx_wave_t
      read(9)ky_wave_t
      read(9)twox_wave_t
      read(9)twoy_wave_t
      read(9)tawx_wave_t
      read(9)tawy_wave_t
      read(9)fluxbar_u
      read(9)fluxbar_v
      read(9)dir_wave_t
      read(9)velbarstokes_u
      read(9)velbarstokes_v
      read(9)ustokesvortex_t
      read(9)ustokesvortex_f
      read(9)vstokesvortex_t
      read(9)vstokesvortex_f
      read(9)fluxbarsave_u
      read(9)fluxbarsave_v
      read(9)sshsave_u
      read(9)sshsave_v
      read(9)sshsave_w
      read(9)fluxbar_sumt_u
      read(9)fluxbar_sumt_v
      read(9)velavr_u
      read(9)velavr_v
      read(9)timefilter_u
      read(9)timefilter_v
      read(9)wetmask_u
      read(9)wetmask_v
      read(9)wetmask_t
      read(9)fluxbarsum_ofl_u
      read(9)fluxbarsum_ofl_v
      read(9)extavera_u
      read(9)extavera_v
      read(9)sponge_u
      read(9)sponge_v
      read(9)anyvar3d
      read(9)anyvar2d
      read(9)sshobc_w
      read(9)velbarobc_u
      read(9)velbarobc_v
      read(9)xy_u
      read(9)xy_v
      read(9)xy_t
      read(9)xy_f
      read(9)q10_t
      read(9)teta10_t
      read(9)wstress_u
      read(9)wstress_v
      read(9)sshf_w
      read(9)slhf_w
      read(9)teta2_t
      read(9)q2_t
      read(9)pss_w
      read(9)uwind_t
      read(9)vwind_t
      read(9)tetastar_t
      read(9)ustar_t
      read(9)qstar_t
      read(9)riverdir
      read(9)l_river
      read(9)river_no
      read(9)river_dom
      read(9)jpm
      read(9)nest_len_in
      read(9)iriver
      read(9)jriver
      read(9)riverdt
      read(9)river_s
      read(9)river_tmin
      read(9)river_tmax
      read(9)hriver
      read(9)friver
      read(9)realriver
      read(9)riverinfo
      read(9)river_timeref
      read(9)river_t
      read(9)riverflux
      read(9)obc_hf_dt
      read(9)cwi_int_u
      read(9)cwi_int_v
      read(9)cwj_int_u
      read(9)cwj_int_v
      read(9)sshrefobc_i
      read(9)vbrrefobc_i
      read(9)sshrefobc_j
      read(9)vbrrefobc_j
      read(9)sshrefsave_i
      read(9)vbrrefsave_i
      read(9)sshrefsave_j
      read(9)vbrrefsave_j
      read(9)grdobc3d_j
      read(9)grdobc3d_i
      read(9)obcmode_u
      read(9)hr_z2lr_w
      read(9)bouee_t
      read(9)spo_i1_u
      read(9)spo_i2_u
      read(9)spo_j1_u
      read(9)spo_j2_u
      read(9)spo_i1_v
      read(9)spo_i2_v
      read(9)spo_j1_v
      read(9)spo_j2_v
      read(9)spo_i1_t
      read(9)spo_i2_t
      read(9)spo_j1_t
      read(9)spo_j2_t
      read(9)obcstreamf
      read(9)mask_i_w
      read(9)mask_i_v
      read(9)mask_i_u
      read(9)mask_j_w
      read(9)mask_j_u
      read(9)mask_j_v
      read(9)kmin_u
      read(9)kmin_v
      read(9)kmin_w
      read(9)l2ij_out_u
      read(9)l2ij_out_v
      read(9)l2ij_out_w
      read(9)l2ij_in_u
      read(9)l2ij_in_v
      read(9)l2ij_in_w
      read(9)fillmask_t
      read(9)profshear
      read(9)passebas
      read(9)passehaut
      read(9)daysim
      read(9)obcinfo
      read(9)offlinedt
      read(9)kdate_output
      read(9)pss_mean
      read(9)sshobc_cum
      read(9)nest_dt_in
      read(9)nest_dt_out
      read(9)obcafdt
      read(9)wavedt
      read(9)anyv1d
      read(9)airseainfo
      read(9)nestedcorner
      read(9)gridcard
      read(9)proficard
      read(9)novector
      read(9)ctdcard_w
      read(9)coefmat
      read(9)dayindex
      read(9)datetide
      read(9)grh_out_var
      read(9)varid
      read(9)grh_nb
      read(9)airseadt
      read(9)datesim
      read(9)dateobc
      read(9)dateairsea
      read(9)dateriver
      read(9)vardim
      read(9)varstart
      read(9)varcount
      read(9)karman
      read(9)stefan
      read(9)ce
      read(9)cen
      read(9)ch
      read(9)chn
      read(9)cd
      read(9)cdn
      read(9)z_2
      read(9)z_10
      read(9)uv_10
      read(9)q_0
      read(9)r_0
      read(9)pvs_0
      read(9)psih_10
      read(9)psih_2
      read(9)phim
      read(9)zl_10
      read(9)zl_2
      read(9)falpha
      read(9)fbeta
      read(9)ro
      read(9)cp_air
      read(9)lv
      read(9)psim_10
      read(9)psim_2
      read(9)loop1
      read(9)loop2
      read(9)loop3
      read(9)nairsea
      read(9)bi_onoff
      read(9)nc_or_bin_airsea
      read(9)loop_graph
      read(9)kount_var
      read(9)rayonterre
      read(9)pole_lon
      read(9)pole_lat
      read(9)y0
      read(9)phi0
      read(9)longi
      read(9)latit
      read(9)longi0
      read(9)latit0
      read(9)longi1
      read(9)latit1
      read(9)angle0
      read(9)assel0
      read(9)assel1
      read(9)assel2
      read(9)assel3
      read(9)alp_t
      read(9)alp_s
      read(9)pi
      read(9)grav
      read(9)rho
      read(9)rhoair
      read(9)valmax
      read(9)vis
      read(9)wetdry_cst1
      read(9)wetdry_cst2
      read(9)wetdry_cst3
      read(9)tkee1
      read(9)tkee2
      read(9)tkee3
      read(9)tkeg2
      read(9)tkeg3
      read(9)tkeg4
      read(9)tkeg5
      read(9)tkeg6
      read(9)tkeb1
      read(9)tkeb2
      read(9)ctke1
      read(9)ctke2
      read(9)t0
      read(9)s0
      read(9)cp
      read(9)absorption
      read(9)light_att1
      read(9)light_att2
      read(9)light_rat1
      read(9)light_rat2
      read(9)z0mer
      read(9)z0s
      read(9)sponge_l
      read(9)t0_base
      read(9)s0_base
      read(9)rho_base
      read(9)alp_t_base
      read(9)alp_s_base
      read(9)zero
      read(9)un
      read(9)hstepmin
      read(9)hstepmax
      read(9)cfl_sshmax
      read(9)cfl_umax
      read(9)cfl_reduce
      read(9)tfc1
      read(9)tfc2
      read(9)ihmax
      read(9)jhmax
      read(9)ihmin
      read(9)jhmin
      read(9)convect_yn
      read(9)nbvstepmin
      read(9)unit_r4
      read(9)x1_r4
      read(9)x2_r4
      read(9)x3_r4
      read(9)discharge
      read(9)filval
      read(9)dxb
      read(9)dyb
      read(9)dxa
      read(9)dya
      read(9)dti_fw
      read(9)dt_obc
      read(9)dti_lp
      read(9)dte_lp
      read(9)hmax
      read(9)hmin
      read(9)h1d
      read(9)heure
      read(9)dist
      read(9)dist0
      read(9)dist1
      read(9)dist2
      read(9)dist3
      read(9)x0
      read(9)x1
      read(9)x2
      read(9)x3
      read(9)x4
      read(9)x5
      read(9)x6
      read(9)x7
      read(9)x8
      read(9)x9
      read(9)x10
      read(9)x11
      read(9)x12
      read(9)x13
      read(9)x14
      read(9)x20
      read(9)x21
      read(9)x22
      read(9)x33
      read(9)x44
      read(9)cdseuil
      read(9)dlon
      read(9)dlat
      read(9)epsi
      read(9)lagrange_ssh
      read(9)relax_es
      read(9)relax_ext
      read(9)relax_int
      read(9)relax_ts
      read(9)relax_bpc
      read(9)diffu
      read(9)difnorm
      read(9)h_inf
      read(9)h_sup
      read(9)lup
      read(9)ldown
      read(9)zup
      read(9)zdown
      read(9)sol1
      read(9)sol2
      read(9)profm1
      read(9)profp1
      read(9)coa
      read(9)cob
      read(9)coc
      read(9)suma
      read(9)sumb
      read(9)discri
      read(9)const1
      read(9)const2
      read(9)const3
      read(9)const4
      read(9)const5
      read(9)const6
      read(9)const7
      read(9)const8
      read(9)const9
      read(9)rap
      read(9)rap_obc
      read(9)rapi
      read(9)rapj
      read(9)rapk
      read(9)rbase
      read(9)small
      read(9)small1
      read(9)small3
      read(9)emin
      read(9)hgesig
      read(9)pgesig
      read(9)windfactor
      read(9)sumarchive
      read(9)deci
      read(9)decj
      read(9)deck
      read(9)xdtk_out
      read(9)tfond
      read(9)sfond
      read(9)rfond
      read(9)geostrodope
      read(9)c1streamf
      read(9)c2streamf
      read(9)rampe
      read(9)y1
      read(9)y2
      read(9)sum_mi
      read(9)obc_hf_reset
      read(9)rho_0d
      read(9)tem_0d
      read(9)sal_0d
      read(9)t0surf
      read(9)s0surf
      read(9)rho_tmp
      read(9)cst_adv_hor
      read(9)cst_adv_ver
      read(9)cst_adv_vel
      read(9)zmin
      read(9)zmax
      read(9)z1
      read(9)z2
      read(9)ssh_avr_nest_out
      read(9)grid_area
      read(9)grid_areaglb
      read(9)deg2rad
      read(9)rad2deg
      read(9)kountgraph
      read(9)kounttide_prev_rdv
      read(9)kounttide_next_rdv
      read(9)rap_wave
      read(9)i
      read(9)j
      read(9)k
      read(9)flag3d
      read(9)lrec
      read(9)ifilm
      read(9)kount
      read(9)compt1
      read(9)compt2
      read(9)compt3
      read(9)compt4
      read(9)kount0
      read(9)kount1
      read(9)kount2
      read(9)kount3
      read(9)kount4
      read(9)kount5
      read(9)kount6
      read(9)kount7
      read(9)kount8
      read(9)kount9
      read(9)kountmod
      read(9)kountrdv1
      read(9)kountrdv2
      read(9)kountrdv3
      read(9)kountrdv4
      read(9)kount0_rst
      read(9)jour
      read(9)kstop
      read(9)kpvwave
      read(9)give_chanel9
      read(9)i0
      read(9)j0
      read(9)k2dini
      read(9)k2dfin
      read(9)k2dite
      read(9)i2dh
      read(9)l1
      read(9)l1_sca
      read(9)l1_vec
      read(9)l2
      read(9)l2_sca
      read(9)l2_vec
      read(9)l3
      read(9)l3_sca
      read(9)l3_vec
      read(9)len1
      read(9)nc
      read(9)nc1
      read(9)initial
      read(9)itimets
      read(9)itimebio
      read(9)iadvec_ts
      read(9)iturbulence
      read(9)istreamf
      read(9)itime
      read(9)kts
      read(9)kuv
      read(9)ko
      read(9)jm1
      read(9)jp1
      read(9)jp2
      read(9)im1
      read(9)ip1
      read(9)ip2
      read(9)iwind
      read(9)ip
      read(9)im
      read(9)jp
      read(9)jm
      read(9)kp
      read(9)km
      read(9)ipnoc
      read(9)i1
      read(9)i2
      read(9)i3
      read(9)i4
      read(9)i5
      read(9)i6
      read(9)i7
      read(9)i8
      read(9)i9
      read(9)i10
      read(9)j1
      read(9)j2
      read(9)j3
      read(9)j4
      read(9)j5
      read(9)j6
      read(9)j7
      read(9)j8
      read(9)j9
      read(9)k0
      read(9)k1
      read(9)k2
      read(9)k3
      read(9)k4
      read(9)k5
      read(9)k6
      read(9)k7
      read(9)k8
      read(9)k9
      read(9)kr
      read(9)kp1
      read(9)km1
      read(9)itest
      read(9)itest1
      read(9)itest2
      read(9)itest3
      read(9)ioption
      read(9)nsmooth
      read(9)kp2
      read(9)nriver
      read(9)ian0
      read(9)imois0
      read(9)ijour0
      read(9)iheure0
      read(9)iminute0
      read(9)iseconde0
      read(9)iref
      read(9)jref
      read(9)lname1
      read(9)lname2
      read(9)lname3
      read(9)lname4
      read(9)kmode
      read(9)kmodemax
      read(9)typegrid
      read(9)istar
      read(9)jstar
      read(9)istop
      read(9)jstop
      read(9)izoomin
      read(9)izoomax
      read(9)jzoomin
      read(9)jzoomax
      read(9)iairsea
      read(9)ialbedo
      read(9)airseaoption
      read(9)iobc_f
      read(9)iobc_wv
      read(9)iobc_ogcm
      read(9)iobc_lr
      read(9)obc_option
      read(9)iobc_demo_wv
      read(9)iarchive
      read(9)imodeltrc
      read(9)imodelbio
      read(9)multiple
      read(9)kvarmax
      read(9)igesig
      read(9)isigfile
      read(9)ksecu
      read(9)kmaxtide
      read(9)kminserie
      read(9)nzctdmax
      read(9)nsctdmax
      read(9)ktctdmin
      read(9)ktctdmax
      read(9)kdtk_out
      read(9)k10
      read(9)k11
      read(9)nbinco
      read(9)nbequa
      read(9)nbsparse
      read(9)kland
      read(9)tidestep2
      read(9)tidestep3
      read(9)ncfilm_max
      read(9)in_out_tide
      read(9)ioffline
      read(9)kmax_dof
      read(9)k_in
      read(9)k_out
      read(9)idate_output
      read(9)ihybsig
      read(9)nhybsig
      read(9)tke_surf
      read(9)grh_out_mi
      read(9)nest_onoff_in
      read(9)nest_onoff_demo
      read(9)nest_full_in
      read(9)nest_full_out
      read(9)nest_onoff_out
      read(9)ncmin_airsea
      read(9)ncmin_river
      read(9)ncmin_af
      read(9)ncmax_af
      read(9)eqs_state1
      read(9)eqs_state2
      read(9)eqs_state3
      read(9)obcfreeorfix
      read(9)iwve
      read(9)dataperwavefile
      read(9)sp_or_db
      read(9)kbu
      read(9)kbumax
      read(9)bouee_modulo
      read(9)n_element
      read(9)relaxtype_ts
      read(9)obctype_ts
      read(9)obctype_p
      read(9)restart_file_y_or_n
      read(9)ncid
      read(9)x_xhl_dim
      read(9)y_xhl_dim
      read(9)z_xhl_dim
      read(9)x_yhl_dim
      read(9)y_yhl_dim
      read(9)z_yhl_dim
      read(9)x_zhl_dim
      read(9)y_zhl_dim
      read(9)z_zhl_dim
      read(9)x_zl_dim
      read(9)y_zl_dim
      read(9)z_zl_dim
      read(9)time_dim
      read(9)dayindex_size
      read(9)tide_year_min
      read(9)tide_year_max
      read(9)irelaxsst
      read(9)nest_len_out
      read(9)ind
      read(9)som0
      read(9)som2
      read(9)b2delev
      read(9)b2delev_glb
      read(9)sum0
      read(9)sum1
      read(9)sum2
      read(9)sum3
      read(9)sum4
      read(9)sum5
      read(9)sum6
      read(9)sum7
      read(9)sum8
      read(9)sum9
      read(9)sum10
      read(9)sum11
      read(9)sum12
      read(9)sum13
      read(9)time1
      read(9)time2
      read(9)small2
      read(9)x1_r8
      read(9)x2_r8
      read(9)x3_r8
      read(9)x4_r8
      read(9)sum0glb
      read(9)sum1glb
      read(9)sum2glb
      read(9)sum3glb
      read(9)sum4glb
      read(9)sum5glb
      read(9)sum6glb
      read(9)lonmin
      read(9)lonmax
      read(9)latmin
      read(9)latmax
! insere partie_lit_1 fin. SURTOUT NE PAS EFFACER CETTE LIGNE

      close(9)
      write(6,*)'lecture chanel9 fin.'

      endif                  !§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§>   !

      if (ichoix.eq.2.or.ichoix.eq.22) then                            !
       if(ichoix.eq.2)texte60='restart_output/chanel9_'//dom_c         !
      if(ichoix.eq.22)texte60='restart_output/chanelbio_'//dom_c       !

      if(ichanel9.eq.2) then !>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>!

      if(kount.eq.kount1.or.                                            &
         kount.eq.kount2.or.                                            &
         kount.eq.kount3.or.                                            &
         kount.eq.kount4.or.                                            &
         kount.eq.kount5.or.                                            &
         kount.eq.kount6.or.                                            &
         kount.eq.kount7.or.                                            &
         kount.eq.kount8)then !------------------------------------->

! calcul de la date                                                    !
      call kount_to_date(kount)

      write(texte80(1),                                                 &
       '(1x,i2,1x,a9,1x,i4,1x,a,i2,a1,i2,a1,i2)')                       &
       i7,month(i6),i5,'h:m:s ',i3,':',i2,':',i1

! puis afficher la date à l'écran:                                     !
      write(6,*)'--------------------------------'
      write(6,*)'fichier hot_restart a la date:'
      write(6,'(a33)')texte80(1)(1:33)

! écrire année année mois dans TEXTE90:                                !
      i0=i7+100*i6+10000*i5
      write(texte90(1:8),'(i8)')i0

! écrire heure seconde minute dans TEXTE90:
      i0=i1+100*i2+10000*i3
      i0=i0+1000000 ! on ajoute cette constante pour forcer            !
                    ! l'ecriture des caracteres "0" qd I0=0
      write(texte90(9:15),'(i7)')i0
! puis on efface le "1" avec un caractere de séparation, "_"
! écrire ":" dans TEXTE90:
      write(texte90(9:9),'(a1)')'_'                                    !

       if(ichoix.eq.2)                                                  &
       texte60='restart_output/chanel9_'//dom_c//'_'//texte90(1:15)    !
      if(ichoix.eq.22)                                                  &
       texte60='restart_output/chanelbio_'//dom_c//'_'//texte90(1:15)  !

      endif                   !------------------------------------->
      endif                  !>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>!


      if(ichoix.eq.22) then !$$$$$$$$$$$$$$$$$$$$$$$>
      open(unit=9,file=texte60                                          &
       ,access='sequential',form='unformatted')
       write(6,'(a12,a50)')'ecriture de ',texte60
       write(9)bio_t
       write(9)biosum_t
       write(9)tendancebio_t
       write(9)fluxbio_w
       write(9)wsed
       write(9)river_bio
       write(9)socard
       write(9)kb
       write(9)kbmax
       write(9)kso
       write(9)ksomax
      close(9)
      endif                 !$$$$$$$$$$$$$$$$$$$$$$$>

      if(ichoix.eq.2) then  !$$$$$$$$$$$$$$$$$$$$$$$>
      open(unit=9,file=texte60                                         & !
       ,access='sequential',form='unformatted')

      write(6,'(a12,a50)')'ecriture de ',texte60
      write(6,*)'debut:'

! insere partie_ecrit_1 debut: SURTOUT NE PAS EFFACER CETTE LIGNE
      write(9)analysetide_u
      write(9)analysetide_v
      write(9)analysetide_w
      write(9)tidepotential_w
      write(9)sshtotide_w
      write(9)sshtidecos_w
      write(9)sshtidesin_w
      write(9)veltidecos_u
      write(9)veltidesin_u
      write(9)veltidecos_v
      write(9)veltidesin_v
      write(9)potidecos_w
      write(9)potidesin_w
      write(9)passetide
      write(9)z1meatide
      write(9)z2meatide
      write(9)frqtide
      write(9)v0tide
      write(9)equitide
      write(9)ftide
      write(9)utide
      write(9)sshmeatide
      write(9)ti0tide
      write(9)tideana_spinup
      write(9)tideana_delta
      write(9)sshtide_cum
      write(9)nutide
      write(9)ktide
      write(9)tideforces
      write(9)tideana_yesno
      write(9)tideana_modulo
      write(9)dz_u
      write(9)dz_v
      write(9)dz_t
      write(9)stokesvortex_u
      write(9)stokesvortex_v
      write(9)depth_t
      write(9)sigma_w
      write(9)dsig_t
      write(9)depth_u
      write(9)depth_v
      write(9)depth_w
      write(9)tridia_out
      write(9)kz_w
      write(9)presgrad_u
      write(9)presgrad_v
      write(9)rhp_t
      write(9)tkll_w
      write(9)tkle_w
      write(9)tken_w
      write(9)mask_t
      write(9)mask_f
      write(9)mask_u
      write(9)mask_v
      write(9)ksl_t
      write(9)vel_u
      write(9)vel_v
      write(9)omega_w
      write(9)veldydz_u
      write(9)veldxdz_v
      write(9)tridia_in
      write(9)tem_t
      write(9)sal_t
      write(9)anyv3d
      write(9)vmi_u
      write(9)vmi_v
      write(9)velobchf_u
      write(9)velobchf_v
      write(9)ssh_obc_hf_w
      write(9)anyvarlr
      write(9)tobc_t
      write(9)sobc_t
      write(9)velobc_u
      write(9)velobc_v
      write(9)dfvofl_w
      write(9)lon_t
      write(9)lat_t
      write(9)lon_u
      write(9)lat_u
      write(9)lon_v
      write(9)lat_v
      write(9)lon_f
      write(9)lat_f
      write(9)fric_u
      write(9)fric_v
      write(9)fric_t
      write(9)velbot3d2d_u
      write(9)velbot3d2d_v
      write(9)cdb_t
      write(9)xflux_t
      write(9)xflux_f
      write(9)yflux_t
      write(9)yflux_f
      write(9)h_w
      write(9)h_u
      write(9)h_v
      write(9)h_f
      write(9)coriolis_t
      write(9)pres3d2d_u
      write(9)pres3d2d_v
      write(9)adve3d2d_u
      write(9)adve3d2d_v
      write(9)dif3d2d_u
      write(9)dif3d2d_v
      write(9)stokesvortex3d2d_u
      write(9)stokesvortex3d2d_v
      write(9)wstress_w
      write(9)z0_w
      write(9)dx_u
      write(9)dx_v
      write(9)dx_t
      write(9)dx_f
      write(9)dy_u
      write(9)dy_v
      write(9)dy_t
      write(9)dy_f
      write(9)dxdy_u
      write(9)dxdy_v
      write(9)dxdy_t
      write(9)albedo_w
      write(9)gridrotcos_t
      write(9)gridrotsin_t
      write(9)sshstokes_w
      write(9)velbar_u
      write(9)velbar_v
      write(9)ssh_ext_w
      write(9)ssh_int_u
      write(9)ssh_int_v
      write(9)ssh_int_w
      write(9)streamf_f
      write(9)hz_u
      write(9)hzdy_u
      write(9)hz_v
      write(9)hzdx_v
      write(9)hz_w
      write(9)vsumsave_u
      write(9)vsumsave_v
      write(9)ssr_w
      write(9)snsf_w
      write(9)precipi_w
      write(9)hssh_w
      write(9)sponge_t
      write(9)zeroleveldepth_u
      write(9)zeroleveldepth_v
      write(9)heatrelax_w
      write(9)velstokes_u
      write(9)velstokes_v
      write(9)t_wave_t
      write(9)hs_wave_t
      write(9)kx_wave_t
      write(9)ky_wave_t
      write(9)twox_wave_t
      write(9)twoy_wave_t
      write(9)tawx_wave_t
      write(9)tawy_wave_t
      write(9)fluxbar_u
      write(9)fluxbar_v
      write(9)dir_wave_t
      write(9)velbarstokes_u
      write(9)velbarstokes_v
      write(9)ustokesvortex_t
      write(9)ustokesvortex_f
      write(9)vstokesvortex_t
      write(9)vstokesvortex_f
      write(9)fluxbarsave_u
      write(9)fluxbarsave_v
      write(9)sshsave_u
      write(9)sshsave_v
      write(9)sshsave_w
      write(9)fluxbar_sumt_u
      write(9)fluxbar_sumt_v
      write(9)velavr_u
      write(9)velavr_v
      write(9)timefilter_u
      write(9)timefilter_v
      write(9)wetmask_u
      write(9)wetmask_v
      write(9)wetmask_t
      write(9)fluxbarsum_ofl_u
      write(9)fluxbarsum_ofl_v
      write(9)extavera_u
      write(9)extavera_v
      write(9)sponge_u
      write(9)sponge_v
      write(9)anyvar3d
      write(9)anyvar2d
      write(9)sshobc_w
      write(9)velbarobc_u
      write(9)velbarobc_v
      write(9)xy_u
      write(9)xy_v
      write(9)xy_t
      write(9)xy_f
      write(9)q10_t
      write(9)teta10_t
      write(9)wstress_u
      write(9)wstress_v
      write(9)sshf_w
      write(9)slhf_w
      write(9)teta2_t
      write(9)q2_t
      write(9)pss_w
      write(9)uwind_t
      write(9)vwind_t
      write(9)tetastar_t
      write(9)ustar_t
      write(9)qstar_t
      write(9)riverdir
      write(9)l_river
      write(9)river_no
      write(9)river_dom
      write(9)jpm
      write(9)nest_len_in
      write(9)iriver
      write(9)jriver
      write(9)riverdt
      write(9)river_s
      write(9)river_tmin
      write(9)river_tmax
      write(9)hriver
      write(9)friver
      write(9)realriver
      write(9)riverinfo
      write(9)river_timeref
      write(9)river_t
      write(9)riverflux
      write(9)obc_hf_dt
      write(9)cwi_int_u
      write(9)cwi_int_v
      write(9)cwj_int_u
      write(9)cwj_int_v
      write(9)sshrefobc_i
      write(9)vbrrefobc_i
      write(9)sshrefobc_j
      write(9)vbrrefobc_j
      write(9)sshrefsave_i
      write(9)vbrrefsave_i
      write(9)sshrefsave_j
      write(9)vbrrefsave_j
      write(9)grdobc3d_j
      write(9)grdobc3d_i
      write(9)obcmode_u
      write(9)hr_z2lr_w
      write(9)bouee_t
      write(9)spo_i1_u
      write(9)spo_i2_u
      write(9)spo_j1_u
      write(9)spo_j2_u
      write(9)spo_i1_v
      write(9)spo_i2_v
      write(9)spo_j1_v
      write(9)spo_j2_v
      write(9)spo_i1_t
      write(9)spo_i2_t
      write(9)spo_j1_t
      write(9)spo_j2_t
      write(9)obcstreamf
      write(9)mask_i_w
      write(9)mask_i_v
      write(9)mask_i_u
      write(9)mask_j_w
      write(9)mask_j_u
      write(9)mask_j_v
      write(9)kmin_u
      write(9)kmin_v
      write(9)kmin_w
      write(9)l2ij_out_u
      write(9)l2ij_out_v
      write(9)l2ij_out_w
      write(9)l2ij_in_u
      write(9)l2ij_in_v
      write(9)l2ij_in_w
      write(9)fillmask_t
      write(9)profshear
      write(9)passebas
      write(9)passehaut
      write(9)daysim
      write(9)obcinfo
      write(9)offlinedt
      write(9)kdate_output
      write(9)pss_mean
      write(9)sshobc_cum
      write(9)nest_dt_in
      write(9)nest_dt_out
      write(9)obcafdt
      write(9)wavedt
      write(9)anyv1d
      write(9)airseainfo
      write(9)nestedcorner
      write(9)gridcard
      write(9)proficard
      write(9)novector
      write(9)ctdcard_w
      write(9)coefmat
      write(9)dayindex
      write(9)datetide
      write(9)grh_out_var
      write(9)varid
      write(9)grh_nb
      write(9)airseadt
      write(9)datesim
      write(9)dateobc
      write(9)dateairsea
      write(9)dateriver
      write(9)vardim
      write(9)varstart
      write(9)varcount
      write(9)karman
      write(9)stefan
      write(9)ce
      write(9)cen
      write(9)ch
      write(9)chn
      write(9)cd
      write(9)cdn
      write(9)z_2
      write(9)z_10
      write(9)uv_10
      write(9)q_0
      write(9)r_0
      write(9)pvs_0
      write(9)psih_10
      write(9)psih_2
      write(9)phim
      write(9)zl_10
      write(9)zl_2
      write(9)falpha
      write(9)fbeta
      write(9)ro
      write(9)cp_air
      write(9)lv
      write(9)psim_10
      write(9)psim_2
      write(9)loop1
      write(9)loop2
      write(9)loop3
      write(9)nairsea
      write(9)bi_onoff
      write(9)nc_or_bin_airsea
      write(9)loop_graph
      write(9)kount_var
      write(9)rayonterre
      write(9)pole_lon
      write(9)pole_lat
      write(9)y0
      write(9)phi0
      write(9)longi
      write(9)latit
      write(9)longi0
      write(9)latit0
      write(9)longi1
      write(9)latit1
      write(9)angle0
      write(9)assel0
      write(9)assel1
      write(9)assel2
      write(9)assel3
      write(9)alp_t
      write(9)alp_s
      write(9)pi
      write(9)grav
      write(9)rho
      write(9)rhoair
      write(9)valmax
      write(9)vis
      write(9)wetdry_cst1
      write(9)wetdry_cst2
      write(9)wetdry_cst3
      write(9)tkee1
      write(9)tkee2
      write(9)tkee3
      write(9)tkeg2
      write(9)tkeg3
      write(9)tkeg4
      write(9)tkeg5
      write(9)tkeg6
      write(9)tkeb1
      write(9)tkeb2
      write(9)ctke1
      write(9)ctke2
      write(9)t0
      write(9)s0
      write(9)cp
      write(9)absorption
      write(9)light_att1
      write(9)light_att2
      write(9)light_rat1
      write(9)light_rat2
      write(9)z0mer
      write(9)z0s
      write(9)sponge_l
      write(9)t0_base
      write(9)s0_base
      write(9)rho_base
      write(9)alp_t_base
      write(9)alp_s_base
      write(9)zero
      write(9)un
      write(9)hstepmin
      write(9)hstepmax
      write(9)cfl_sshmax
      write(9)cfl_umax
      write(9)cfl_reduce
      write(9)tfc1
      write(9)tfc2
      write(9)ihmax
      write(9)jhmax
      write(9)ihmin
      write(9)jhmin
      write(9)convect_yn
      write(9)nbvstepmin
      write(9)unit_r4
      write(9)x1_r4
      write(9)x2_r4
      write(9)x3_r4
      write(9)discharge
      write(9)filval
      write(9)dxb
      write(9)dyb
      write(9)dxa
      write(9)dya
      write(9)dti_fw
      write(9)dt_obc
      write(9)dti_lp
      write(9)dte_lp
      write(9)hmax
      write(9)hmin
      write(9)h1d
      write(9)heure
      write(9)dist
      write(9)dist0
      write(9)dist1
      write(9)dist2
      write(9)dist3
      write(9)x0
      write(9)x1
      write(9)x2
      write(9)x3
      write(9)x4
      write(9)x5
      write(9)x6
      write(9)x7
      write(9)x8
      write(9)x9
      write(9)x10
      write(9)x11
      write(9)x12
      write(9)x13
      write(9)x14
      write(9)x20
      write(9)x21
      write(9)x22
      write(9)x33
      write(9)x44
      write(9)cdseuil
      write(9)dlon
      write(9)dlat
      write(9)epsi
      write(9)lagrange_ssh
      write(9)relax_es
      write(9)relax_ext
      write(9)relax_int
      write(9)relax_ts
      write(9)relax_bpc
      write(9)diffu
      write(9)difnorm
      write(9)h_inf
      write(9)h_sup
      write(9)lup
      write(9)ldown
      write(9)zup
      write(9)zdown
      write(9)sol1
      write(9)sol2
      write(9)profm1
      write(9)profp1
      write(9)coa
      write(9)cob
      write(9)coc
      write(9)suma
      write(9)sumb
      write(9)discri
      write(9)const1
      write(9)const2
      write(9)const3
      write(9)const4
      write(9)const5
      write(9)const6
      write(9)const7
      write(9)const8
      write(9)const9
      write(9)rap
      write(9)rap_obc
      write(9)rapi
      write(9)rapj
      write(9)rapk
      write(9)rbase
      write(9)small
      write(9)small1
      write(9)small3
      write(9)emin
      write(9)hgesig
      write(9)pgesig
      write(9)windfactor
      write(9)sumarchive
      write(9)deci
      write(9)decj
      write(9)deck
      write(9)xdtk_out
      write(9)tfond
      write(9)sfond
      write(9)rfond
      write(9)geostrodope
      write(9)c1streamf
      write(9)c2streamf
      write(9)rampe
      write(9)y1
      write(9)y2
      write(9)sum_mi
      write(9)obc_hf_reset
      write(9)rho_0d
      write(9)tem_0d
      write(9)sal_0d
      write(9)t0surf
      write(9)s0surf
      write(9)rho_tmp
      write(9)cst_adv_hor
      write(9)cst_adv_ver
      write(9)cst_adv_vel
      write(9)zmin
      write(9)zmax
      write(9)z1
      write(9)z2
      write(9)ssh_avr_nest_out
      write(9)grid_area
      write(9)grid_areaglb
      write(9)deg2rad
      write(9)rad2deg
      write(9)kountgraph
      write(9)kounttide_prev_rdv
      write(9)kounttide_next_rdv
      write(9)rap_wave
      write(9)i
      write(9)j
      write(9)k
      write(9)flag3d
      write(9)lrec
      write(9)ifilm
      write(9)kount
      write(9)compt1
      write(9)compt2
      write(9)compt3
      write(9)compt4
      write(9)kount0
      write(9)kount1
      write(9)kount2
      write(9)kount3
      write(9)kount4
      write(9)kount5
      write(9)kount6
      write(9)kount7
      write(9)kount8
      write(9)kount9
      write(9)kountmod
      write(9)kountrdv1
      write(9)kountrdv2
      write(9)kountrdv3
      write(9)kountrdv4
      write(9)kount0_rst
      write(9)jour
      write(9)kstop
      write(9)kpvwave
      write(9)give_chanel9
      write(9)i0
      write(9)j0
      write(9)k2dini
      write(9)k2dfin
      write(9)k2dite
      write(9)i2dh
      write(9)l1
      write(9)l1_sca
      write(9)l1_vec
      write(9)l2
      write(9)l2_sca
      write(9)l2_vec
      write(9)l3
      write(9)l3_sca
      write(9)l3_vec
      write(9)len1
      write(9)nc
      write(9)nc1
      write(9)initial
      write(9)itimets
      write(9)itimebio
      write(9)iadvec_ts
      write(9)iturbulence
      write(9)istreamf
      write(9)itime
      write(9)kts
      write(9)kuv
      write(9)ko
      write(9)jm1
      write(9)jp1
      write(9)jp2
      write(9)im1
      write(9)ip1
      write(9)ip2
      write(9)iwind
      write(9)ip
      write(9)im
      write(9)jp
      write(9)jm
      write(9)kp
      write(9)km
      write(9)ipnoc
      write(9)i1
      write(9)i2
      write(9)i3
      write(9)i4
      write(9)i5
      write(9)i6
      write(9)i7
      write(9)i8
      write(9)i9
      write(9)i10
      write(9)j1
      write(9)j2
      write(9)j3
      write(9)j4
      write(9)j5
      write(9)j6
      write(9)j7
      write(9)j8
      write(9)j9
      write(9)k0
      write(9)k1
      write(9)k2
      write(9)k3
      write(9)k4
      write(9)k5
      write(9)k6
      write(9)k7
      write(9)k8
      write(9)k9
      write(9)kr
      write(9)kp1
      write(9)km1
      write(9)itest
      write(9)itest1
      write(9)itest2
      write(9)itest3
      write(9)ioption
      write(9)nsmooth
      write(9)kp2
      write(9)nriver
      write(9)ian0
      write(9)imois0
      write(9)ijour0
      write(9)iheure0
      write(9)iminute0
      write(9)iseconde0
      write(9)iref
      write(9)jref
      write(9)lname1
      write(9)lname2
      write(9)lname3
      write(9)lname4
      write(9)kmode
      write(9)kmodemax
      write(9)typegrid
      write(9)istar
      write(9)jstar
      write(9)istop
      write(9)jstop
      write(9)izoomin
      write(9)izoomax
      write(9)jzoomin
      write(9)jzoomax
      write(9)iairsea
      write(9)ialbedo
      write(9)airseaoption
      write(9)iobc_f
      write(9)iobc_wv
      write(9)iobc_ogcm
      write(9)iobc_lr
      write(9)obc_option
      write(9)iobc_demo_wv
      write(9)iarchive
      write(9)imodeltrc
      write(9)imodelbio
      write(9)multiple
      write(9)kvarmax
      write(9)igesig
      write(9)isigfile
      write(9)ksecu
      write(9)kmaxtide
      write(9)kminserie
      write(9)nzctdmax
      write(9)nsctdmax
      write(9)ktctdmin
      write(9)ktctdmax
      write(9)kdtk_out
      write(9)k10
      write(9)k11
      write(9)nbinco
      write(9)nbequa
      write(9)nbsparse
      write(9)kland
      write(9)tidestep2
      write(9)tidestep3
      write(9)ncfilm_max
      write(9)in_out_tide
      write(9)ioffline
      write(9)kmax_dof
      write(9)k_in
      write(9)k_out
      write(9)idate_output
      write(9)ihybsig
      write(9)nhybsig
      write(9)tke_surf
      write(9)grh_out_mi
      write(9)nest_onoff_in
      write(9)nest_onoff_demo
      write(9)nest_full_in
      write(9)nest_full_out
      write(9)nest_onoff_out
      write(9)ncmin_airsea
      write(9)ncmin_river
      write(9)ncmin_af
      write(9)ncmax_af
      write(9)eqs_state1
      write(9)eqs_state2
      write(9)eqs_state3
      write(9)obcfreeorfix
      write(9)iwve
      write(9)dataperwavefile
      write(9)sp_or_db
      write(9)kbu
      write(9)kbumax
      write(9)bouee_modulo
      write(9)n_element
      write(9)relaxtype_ts
      write(9)obctype_ts
      write(9)obctype_p
      write(9)restart_file_y_or_n
      write(9)ncid
      write(9)x_xhl_dim
      write(9)y_xhl_dim
      write(9)z_xhl_dim
      write(9)x_yhl_dim
      write(9)y_yhl_dim
      write(9)z_yhl_dim
      write(9)x_zhl_dim
      write(9)y_zhl_dim
      write(9)z_zhl_dim
      write(9)x_zl_dim
      write(9)y_zl_dim
      write(9)z_zl_dim
      write(9)time_dim
      write(9)dayindex_size
      write(9)tide_year_min
      write(9)tide_year_max
      write(9)irelaxsst
      write(9)nest_len_out
      write(9)ind
      write(9)som0
      write(9)som2
      write(9)b2delev
      write(9)b2delev_glb
      write(9)sum0
      write(9)sum1
      write(9)sum2
      write(9)sum3
      write(9)sum4
      write(9)sum5
      write(9)sum6
      write(9)sum7
      write(9)sum8
      write(9)sum9
      write(9)sum10
      write(9)sum11
      write(9)sum12
      write(9)sum13
      write(9)time1
      write(9)time2
      write(9)small2
      write(9)x1_r8
      write(9)x2_r8
      write(9)x3_r8
      write(9)x4_r8
      write(9)sum0glb
      write(9)sum1glb
      write(9)sum2glb
      write(9)sum3glb
      write(9)sum4glb
      write(9)sum5glb
      write(9)sum6glb
      write(9)lonmin
      write(9)lonmax
      write(9)latmin
      write(9)latmax
! insere partie_ecrit_1 fin. SURTOUT NE PAS EFFACER CETTE LIGNE

      close(9)
!     WRITE(6,*)'ecriture de chanel9 terminee'
      write(6,*)'ecriture chanel9 fin.'
      endif                 !$$$$$$$$$$$$$$$$$$$$$$$>

      return
      endif

      return
      end subroutine hot_restart
